#!/bin/bash

#SBATCH --job-name=mcts_test     ## job name
#SBATCH -A NCKAPLAN_LAB     ## Class account to charge resources
#SBATCH -p free                ## partition name
#SBATCH --nodes=1             ## (-N) number of nodes the job will use
#SBATCH --ntasks=1            ## (-n) number of processes to be launched
#SBATCH -c 28                  ## number of cores
#SBATCH --mem=16G
#SBATCH --time 3-00:00:00     ## time limit (1 day?)
#SBATCH --error=logs/slurm-%J.err  ## error log file
#SBATCH --output=logs/slurm-%J.out ## output log file
#SBATCH --mail-type=fail,end
#SBATCH --mail-user=luoninz1@uci.edu

module load miniconda3/24.9.2
source /opt/apps/miniconda3/24.9.2/etc/profile.d/conda.sh
conda activate mcgs-env

# $1 = start value, $2 = step size
python mcts_test_for_smallest_complete_set.py \
    --start "$1" \
    --end 101 \
    --step "$2" \
    --repeat 20 \
    > logs/mcts_n_"$1"-100.log