name: poetry-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # scientific stack via conda (avoid duplicating in pip)
  - numpy
  - scipy=1.16
  - numba=0.61
  - pandas
  - matplotlib
  # dev / tools
  - jupyterlab
  - poetry
  - pip:
      - torch==2.7.1
      - gymnasium==1.1.1
      - stable-baselines3==2.6.0
      - pyvis==0.3.2
      - openai==1.86.0
      - tqdm==4.67.1