name: mcgs-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - tqdm
  - numba
  - matplotlib
  - psutil
  - sympy
  - pip
  - pip:
      - pprintpp  # pprint is built-in, but pprintpp is a pip package if you want enhanced pretty-printing